[tool.poetry]
name = "mycalc"
version = "0.1.0"
description = ""
authors = ["Ganesh Chandrasekaran"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pdoc = "^14.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
